### ISSUE TITLE
Може ли єтот проект помочь мне расшифровать RAW формат? 

### ISSUE THREAD

**Issue by Rombersoft** [jekyll2014/EscPosParser#1]
У меня есть массив байтов, полученньіх снифером с драйвера ОС Windows для принтера Custom VKP80. Так вот, я вижу в конце массива байтов комадьі отрезки и вьіталкивания квитанции. А больше не понимаю где там что. Очень похоже на RAW формат. Можно ли узнать начало и конец єтого RAW формата?

**Comment by jekyll2014** [comment]
Если у Вас правда есть поток байт, то расшифрует. Присылайте, я могу попробовать.

**Comment by Rombersoft** [comment]
[Raw.zip](https://github.com/jekyll2014/EscPosParser/files/7155280/Raw.zip)

**Comment by jekyll2014** [comment]
Для начала надо было получить просто поток данных, а не HTML с кучей ненужной для парсера информации. Тем более, если Вы печатали драйвером, то могли просто перенаправить печать в файл и не заниматься перехватом.
Я выгрыз из одного из Ваших файлов часть данных и запустил расшифровку по ним. Она в автоматическом режиме работает не идеально, т.к. для разных моделей и режимов некоторые команды частично пересекаются сигнатурами. По-хорошему, парсер надо запускать и в ручном режиме смотреть, какие команды он находит и выбирать подошедшие по смыслу, но автомат в целом справляется с выбором наиболее подходящих.
В целом тут все понятно - идут команды настройки принтера, потом печать графики GAM-командами с RLE-сжатием и потом отрез и т.п.
[321.zip](https://github.com/jekyll2014/EscPosParser/files/7158237/321.zip)
К сожалению, я не писал расшифровку GAM-данных пожатых RLE, так что картинку восстановить в автоматическом режиме не удастся. Но и в целом особого смысла расшифровывать данные с драйвера принтера никогда я не видел - драйвер нормально работает, печатает. Вся расшифровка интересна, как правило, в случаях печати напрямую из приложения командами, чтобы понять, что там происходит, получить содержимое и настройки. А в драйвере все это и так в настройках указано.

P.S. Подозреваю, что вот в этом месте данные битые:
[7177]RAW data: "1B 2A 62 00 02 03 FF FF 48 F0 1B 2A 62 38 57 "

**Comment by Rombersoft** [comment]
Я кинул в HTML формате потому что там есть коментарий, который может быть полезен вам. Я отделял от всего HTML только байты, написав парсер, и загонял эти байты повторно только через свою программу - картинка получилась один в один как печать через драйвер, значит данные целы, не битые. Драйвер с ОС Windows XP, а мне надо печать с ОС Arch Linux. Принтер Custom VKP80. Интересно знать алгоритм создания этого масива байтов в драйвере, потому что в документации именно этот способ печати не описан, а именно:
В драйвере 1B 2A 62 X Y, а в документации есть только 1B 2A (0,1,32,33) X Y.
Я подозреваю, что есть некая библиотека в ОС Windows winspool.drv, которая и делает этот RAW формат и которой нет в ОС Linux и исходного кода которой нет в открытом доступе.
https://github.com/mtmsuhail/ESC-POS-USB-NET/issues/17

**Comment by jekyll2014** [comment]
Тут все просто - графику CUSTOM печатает через набор команд GAM (Graphic Advanced Commands) которые не описаны в обычной документации, но на них есть отдельный мануал. Если интересно, то напишите мне в личку (jekyll@mail.ru) - я подскажу, что там и как.
